/*
 * Demo app for json-schema-data-dictionary.
 *
 * No schema editor: users either pick a built-in preset (window.DEMO_PRESETS,
 * generated from tests/fixtures by build-presets.mjs) or upload their own .json
 * files / folders. Each document is handed to the library as { uri, name, schema }
 * with a synthetic uri of https://demo.local/<path> so that relative $refs between
 * documents resolve exactly as they would on disk.
 *
 * Semantic search is opt-in: a model picker (DEMO_MODELS) feeds an embedding worker, and a
 * preset that ships precomputed vectors (demo/vectors, see build-presets.mjs) is searchable
 * without embedding anything in the browser.
 *
 * Automation hooks: session-only URL overrides (see readOverrides) and window.ddDemo.
 */
(function () {
  "use strict";

  var API = window.JsonSchemaDataDictionary;
  var SYNTH_BASE = "https://demo.local/";

  var $ = function (sel) { return document.querySelector(sel); };

  // --- State --------------------------------------------------------------
  var docs = [];            // [{ path, schema }]
  var rootIndex = null;     // null = auto-detect; number = explicit root document
  var docsFromPreset = false;
  var activePreset = null;  // the preset entry behind `docs` while docsFromPreset (carries `vectors`)
  var candidates = [];      // ranked root candidates for `docs` (API.findSchemaRoots), refreshed on every change
  var lastTable = null;
  var lastRenderMs = null;  // wall time of the last renderDataDictionary() call (window.ddDemo.lastRenderMs)

  // Session-only URL overrides (see readOverrides), populated once in start().
  var OVERRIDES = {};

  // Semantic search (opt-in). The model runs in demo/embed-worker.js when Workers are
  // available (not on file://), otherwise on the main thread. The embedder is created once
  // per model and reused across re-renders; the library caches row embeddings in IndexedDB.
  var SEMANTIC_KEY = "dd-demo:semantic";
  var MODEL_KEY = "dd-demo:model";
  var TRANSFORMERS_URL = "https://cdn.jsdelivr.net/npm/@huggingface/transformers@4.2.0";
  // The Pages deploy appends ?v=<commit> to every asset URL (cache-busting). Forward it to
  // the worker so a fresh app.js never pairs with a stale embed-worker.js.
  var ASSET_QUERY = (function () {
    try {
      var src = document.currentScript && document.currentScript.src;
      var m = src && /\?v=[^&#]+/.exec(src);
      return m ? m[0] : "";
    } catch (e) { return ""; }
  })();
  // Models offered by the picker (#semantic-model). Every id must be in the library's
  // KNOWN_EMBEDDING_MODELS table (pooling, prefixes, per-device dtype, cosine floor); ids the
  // running build doesn't know are dropped at start-up. `size` is the download per device.
  var DEMO_MODELS = [
    { id: "MongoDB/mdbr-leaf-ir", label: "LEAF-IR · 23M · Apache-2.0", size: "23 MB q8 / 46 MB fp16", isDefault: true },
    { id: "Xenova/bge-small-en-v1.5", label: "BGE small v1.5 · 33M · MIT", size: "34 MB q8" },
    { id: "Xenova/all-MiniLM-L6-v2", label: "all-MiniLM-L6-v2 · 23M · Apache-2.0", size: "22 MB q8" },
    {
      id: "jinaai/jina-embeddings-v5-text-nano-retrieval",
      label: "Jina v5 nano retrieval · 239M · CC-BY-NC-4.0 · needs WebGPU",
      size: "124 MB q4f16",
      nonCommercial: true,
      needsWebGPU: true,
      notice: "Jina v5 nano is licensed CC-BY-NC-4.0: non-commercial use only."
    }
  ];
  var MODELS = [];               // DEMO_MODELS cross-checked against the library at start-up
  var selectedModel = null;      // the picker's (persisted) choice; the ?model= override wins over it
  var semanticEmbedder = null;   // set once the embedder is loaded and the box is still ticked
  var semanticWorker = null;
  var embedderPromise = null;
  var generation = 0;            // bumped per semantic start; resolutions of older starts are ignored
  var lastSnapshot = null;       // decoded precomputed vectors given to the current render (ddDemo.snapshot)
  var snapshots = {};            // vectors file -> { promise, done, value }: one fetch per file per session
  var eta = null;                // { t0, done0 }: first indexing sample of the current run (ETA baseline)
  var WEBGPU = false;            // a WebGPU adapter can be acquired (probed once in start(); see probeWebGpu)

  // --- Messages -----------------------------------------------------------
  function clearMessages() { $("#messages").replaceChildren(); }
  function addMessage(type, text) {
    var div = document.createElement("div");
    div.className = "message " + type;
    div.textContent = text;
    $("#messages").appendChild(div);
  }

  // --- Presets ------------------------------------------------------------
  // Built-in presets come from presets.js (generated by build-presets.mjs, each with a stable `key`).
  function allPresets() {
    return (window.DEMO_PRESETS || []).slice();
  }

  // Resolve a preset key or index (number or numeric string) to an index into allPresets(); -1 if unknown.
  function findPresetIndex(indexOrKey) {
    var presets = allPresets();
    var s = String(indexOrKey);
    for (var i = 0; i < presets.length; i++) if (presets[i].key === s) return i;
    if (/^\d+$/.test(s) && Number(s) < presets.length) return Number(s);
    return -1;
  }

  function presetValue(p, i) { return p.key || String(i); }

  function populatePresetSelect() {
    var sel = $("#preset-select");
    var presets = allPresets();
    sel.replaceChildren();
    if (!presets.length) {
      var o = document.createElement("option");
      o.textContent = "(no examples available — run npm run demo)";
      sel.appendChild(o);
      sel.disabled = true;
      return;
    }
    presets.forEach(function (p, i) {
      var opt = document.createElement("option");
      opt.value = presetValue(p, i);
      opt.textContent = p.label;
      sel.appendChild(opt);
    });
  }

  // Load a preset by key ("bcrpp") or index. Returns false when unknown.
  function loadPreset(indexOrKey) {
    var presets = allPresets();
    var i = findPresetIndex(indexOrKey);
    var p = presets[i];
    if (!p) return false;
    $("#preset-select").value = presetValue(p, i);
    $("#preset-description").textContent = p.description || "";
    docs = p.documents.map(function (d) { return { path: d.path, schema: d.schema }; });
    docsFromPreset = true;
    activePreset = p;
    rootIndex = null;
    afterDocsChanged();
    return true;
  }

  // --- File / folder ingestion -------------------------------------------
  // Folder uploads (webkitdirectory / dropped directories) prefix every path with the chosen
  // folder's name, and people often hand over a folder well above the schemas — a repository
  // root whose only .json files sit in `study/json_schema/…`. Drop every leading directory the
  // whole selection shares, so the paths line up with the relative $refs (and so dropping
  // "study/" produces exactly what dropping "study/json_schema/" does). Only whole directory
  // segments count, and the last segment (the file name) is never stripped.
  function stripCommonPrefix(paths) {
    if (!paths.length) return paths;
    var common = paths[0].split("/").slice(0, -1);
    for (var i = 1; i < paths.length && common.length; i++) {
      var segs = paths[i].split("/").slice(0, -1);
      var n = 0;
      while (n < common.length && n < segs.length && common[n] === segs[n]) n++;
      common = common.slice(0, n);
    }
    if (!common.length) return paths;
    var cut = common.join("/").length + 1;
    return paths.map(function (p) { return p.slice(cut); });
  }

  function isJson(name) { return /\.json$/i.test(name); }

  // Read + parse a list of { path, file } items, then merge into `docs`. `scanned` is how many
  // files the selection held in total (folder drops), so an all-non-JSON folder says so.
  function ingest(items, scanned, extras) {
    if (!items.length) {
      clearMessages();
      (extras || []).forEach(function (m) { addMessage(m.type, m.text); });
      addMessage("error", scanned
        ? "No .json files found in that selection (" + scanned + " file" + (scanned === 1 ? "" : "s") + " scanned)."
        : "No .json files found in that selection.");
      return Promise.resolve();
    }
    var paths = stripCommonPrefix(items.map(function (it) { return it.path; }));
    var errors = (extras || []).slice();
    var reads = items.map(function (it, k) {
      var path = paths[k];
      return it.file.text().then(
        function (text) {
          try { return { path: path, schema: JSON.parse(text) }; }
          catch (err) {
            errors.push({ type: "error", text: "JSON parse error in “" + path + "”: " + err.message });
            return null;
          }
        },
        function () {
          errors.push({ type: "error", text: "Could not read “" + path + "”." });
          return null;
        }
      );
    });

    return Promise.all(reads).then(function (results) {
      var parsed = results.filter(Boolean);
      if (!parsed.length) {
        clearMessages();
        errors.forEach(function (e) { addMessage(e.type, e.text); });
        return;
      }
      // Uploading replaces a preset, but multiple uploads accumulate into one set.
      if (docsFromPreset) { docs = []; docsFromPreset = false; activePreset = null; }
      parsed.forEach(function (d) {
        var idx = docs.findIndex(function (x) { return x.path === d.path; });
        if (idx >= 0) docs[idx] = d; else docs.push(d);
      });
      // Directory walks arrive in whatever order the browser yields; sort so the document list,
      // the root selector and the auto-detected root do not depend on it.
      docs.sort(function (a, b) { return a.path < b.path ? -1 : a.path > b.path ? 1 : 0; });
      rootIndex = null;
      afterDocsChanged(errors); // surface any per-file parse errors alongside the result
    });
  }

  function addFiles(fileList) {
    var items = Array.prototype.slice.call(fileList)
      .filter(function (f) { return isJson(f.name); })
      .map(function (f) { return { path: f.webkitRelativePath || f.name, file: f }; });
    return ingest(items);
  }

  // Recursively gather files (with relative paths) from a dropped directory entry. Directories
  // nest arbitrarily deep — people drop a repository root, not the schema folder — so the walk
  // has no depth limit; `walk.failures` records the paths the browser refused to read, which is
  // the only clue the user would otherwise get for a half-scanned folder.
  function walkEntry(entry, prefix, walk) {
    return new Promise(function (resolve) {
      if (entry.isFile) {
        entry.file(
          function (file) { walk.files.push({ path: prefix + entry.name, file: file }); resolve(); },
          function () { walk.failures.push(prefix + entry.name); resolve(); }
        );
      } else if (entry.isDirectory) {
        var dir = prefix + entry.name + "/";
        var reader = entry.createReader();
        var readBatch = function () {
          reader.readEntries(function (batch) {
            if (!batch.length) { resolve(); return; }
            Promise.all(batch.map(function (child) { return walkEntry(child, dir, walk); }))
              .then(readBatch); // readEntries yields in chunks; keep going until empty
          }, function () { walk.failures.push(dir); resolve(); });
        };
        readBatch();
      } else {
        resolve();
      }
    });
  }

  function handleDrop(e) {
    var dt = e.dataTransfer;
    var entries = [];
    if (dt.items && dt.items.length && dt.items[0].webkitGetAsEntry) {
      // webkitGetAsEntry() must be called synchronously during the drop event.
      entries = Array.prototype.slice.call(dt.items)
        .map(function (it) { return it.webkitGetAsEntry(); })
        .filter(Boolean);
    }
    if (entries.length) {
      var walk = { files: [], failures: [] };
      Promise.all(entries.map(function (entry) { return walkEntry(entry, "", walk); }))
        .then(function () {
          var json = walk.files.filter(function (c) { return isJson(c.path); });
          var extras = walk.failures.length
            ? [{ type: "warning", text: "Could not read " + walk.failures.length + " item(s) in that folder: " + walk.failures.slice(0, 5).join(", ") + (walk.failures.length > 5 ? ", …" : "") }]
            : [];
          ingest(json, walk.files.length, extras);
        });
    } else if (dt.files && dt.files.length) {
      addFiles(dt.files);
    }
  }

  // --- Manifest + root selector ------------------------------------------
  function renderDocList() {
    var field = $("#doc-list-field");
    var list = $("#doc-list");
    $("#doc-count").textContent = String(docs.length);
    field.hidden = docs.length === 0;
    list.replaceChildren();
    docs.forEach(function (d, i) {
      var li = document.createElement("li");
      var name = document.createElement("span");
      name.className = "doc-path";
      name.textContent = d.path;
      var btn = document.createElement("button");
      btn.type = "button";
      btn.className = "doc-remove";
      btn.dataset.index = String(i);
      btn.setAttribute("aria-label", "Remove " + d.path);
      btn.textContent = "×";
      li.append(name, btn);
      list.appendChild(li);
    });
  }

  // Root selector. A dropped folder can hold dozens of documents, most of them components the
  // root $refs, so the table schemas the library found (findSchemaRoots) come first and the
  // rest sit in a second group. Falls back to a flat list if the running build predates the API.
  function populateRootSelect() {
    var sel = $("#root-select");
    sel.replaceChildren();
    var auto = document.createElement("option");
    auto.value = "";
    auto.textContent = "Auto-detect";
    sel.appendChild(auto);

    var tables = candidates.filter(function (c) { return c.arrayLike && !c.referenced; });
    var isTable = {};
    tables.forEach(function (c) { isTable[c.index] = c; });

    var option = function (i) {
      var o = document.createElement("option");
      o.value = String(i);
      var c = isTable[i];
      o.textContent = c ? docs[i].path + " — " + c.variableCount + " variables" : docs[i].path;
      return o;
    };
    if (tables.length) {
      var main = document.createElement("optgroup");
      main.label = tables.length === 1 ? "Table schema" : "Table schemas";
      tables.forEach(function (c) { main.appendChild(option(c.index)); });
      sel.appendChild(main);
      var rest = document.createElement("optgroup");
      rest.label = "Other documents";
      docs.forEach(function (d, i) { if (!isTable[i]) rest.appendChild(option(i)); });
      if (rest.childElementCount) sel.appendChild(rest);
    } else {
      docs.forEach(function (d, i) { sel.appendChild(option(i)); });
    }
    sel.value = rootIndex == null ? "" : String(rootIndex);
  }

  function removeDoc(i) {
    docs.splice(i, 1);
    rootIndex = null; // indices shifted; fall back to auto-detect
    afterDocsChanged();
  }

  function clearAll() {
    docs = [];
    rootIndex = null;
    docsFromPreset = false;
    activePreset = null;
    afterDocsChanged();
  }

  // --- Build inputs + render ---------------------------------------------
  function buildInputs() {
    return docs.map(function (d) {
      var path = String(d.path || "document.json").replace(/^\/+/, "");
      return {
        uri: SYNTH_BASE + path,
        name: path.split("/").pop() || "document.json",
        schema: d.schema
      };
    });
  }

  function setExportsEnabled(on) {
    $("#download-html-btn").disabled = !on;
    $("#download-csv-btn").disabled = !on;
    // Excel export also needs the (vendored) ExcelJS global to have loaded.
    $("#download-excel-btn").disabled = !on || !window.ExcelJS;
  }

  function afterDocsChanged(extras) {
    candidates = [];
    if (docs.length && typeof API.findSchemaRoots === "function") {
      try { candidates = API.findSchemaRoots(buildInputs()); } catch (e) { candidates = []; }
    }
    renderDocList();
    populateRootSelect();
    render(extras);
  }

  function render(extras) {
    clearMessages();
    (extras || []).forEach(function (m) { addMessage(m.type, m.text); });

    var out = $("#output");
    if (!docs.length) {
      out.replaceChildren();
      lastTable = null;
      lastRenderMs = null;
      lastSnapshot = null;
      setExportsEnabled(false);
      addMessage("info", "Select an example or upload one or more JSON Schema files to begin.");
      return;
    }

    var table;
    try {
      var opts = rootIndex != null ? { rootIndex: rootIndex } : {};
      table = API.schemaDocumentsToTable(buildInputs(), opts);
    } catch (err) {
      out.replaceChildren();
      lastTable = null;
      lastRenderMs = null;
      lastSnapshot = null;
      setExportsEnabled(false);
      addMessage("error", "Couldn’t build the data dictionary: " + err.message);
      return;
    }

    lastTable = table;
    if (!docsFromPreset && !candidates.length && typeof API.findSchemaRoots === "function") {
      addMessage(
        "warning",
        "None of the " + docs.length + " uploaded file" + (docs.length === 1 ? "" : "s") +
          " reads like a JSON Schema (no $schema, type, properties, items …), so the first one was used as the root."
      );
    }
    (table.warnings || []).forEach(function (w) { addMessage("warning", w); });

    var options = {
      // ?shadow=0 forces light DOM until the checkbox is touched (see wire()).
      shadow: OVERRIDES.shadow === false ? false : $("#shadow").checked,
      theme: $("#theme").value,
      expandCategories: $("#expand-categories").checked,
      expandAdditionalInfo: $("#expand-additional").checked
    };
    var semantic = semanticOptions();
    if (semantic) options.semanticSearch = semantic;
    var t0 = performance.now();
    API.renderDataDictionary(out, table, options); // renders synchronously; painting is extra
    lastRenderMs = performance.now() - t0;
    setExportsEnabled(true);
  }

  // --- Semantic search: model picker -------------------------------------
  // Usable WebGPU, as probed at start-up: `navigator.gpu` alone is not enough (Linux Chrome
  // without flags and headless browsers expose it but hand out no adapter).
  function webGpuAvailable() {
    return !OVERRIDES.nogpu && WEBGPU;
  }

  // Resolves with whether a WebGPU adapter can be acquired (the library's detectWebGpu probe).
  // ?nogpu=1 skips it; a build without the probe falls back to the presence of navigator.gpu.
  function probeWebGpu() {
    if (OVERRIDES.nogpu) return Promise.resolve(false);
    var present = typeof navigator !== "undefined" && !!navigator.gpu;
    if (!present || typeof API.detectWebGpu !== "function") return Promise.resolve(present);
    return API.detectWebGpu().then(function (r) { return !!(r && r.available); }, function () { return false; });
  }

  function findModel(id) {
    for (var i = 0; i < MODELS.length; i++) if (MODELS[i].id === id) return MODELS[i];
    return null;
  }

  // Short display name: the label up to its first " · " (e.g. "LEAF-IR").
  function modelName(id) {
    var m = findModel(id);
    return m ? m.label.split(" · ")[0] : id;
  }

  function defaultModelId() {
    for (var i = 0; i < MODELS.length; i++) if (MODELS[i].isDefault) return MODELS[i].id;
    if (findModel(API.DEFAULT_EMBEDDING_MODEL)) return API.DEFAULT_EMBEDDING_MODEL;
    return MODELS.length ? MODELS[0].id : API.DEFAULT_EMBEDDING_MODEL || DEMO_MODELS[0].id;
  }

  // The model the embedder runs: the ?model= override for this session, else the picker's choice.
  function effectiveModel() {
    return OVERRIDES.model || selectedModel || defaultModelId();
  }

  // DEMO_MODELS minus the ids this build of the library doesn't know. A build without the
  // known-models table can't be cross-checked, so it keeps them all.
  function knownDemoModels() {
    var known = API.KNOWN_EMBEDDING_MODELS;
    if (!known) return DEMO_MODELS.slice();
    return DEMO_MODELS.filter(function (m) {
      if (known[m.id]) return true;
      console.warn("[demo] Dropping " + m.id + " from the model picker: not in KNOWN_EMBEDDING_MODELS.");
      return false;
    });
  }

  function populateModelSelect() {
    var sel = $("#semantic-model");
    sel.replaceChildren();
    MODELS.forEach(function (m) {
      var opt = document.createElement("option");
      opt.value = m.id;
      var text = m.label + " (" + m.size + ")";
      if (m.needsWebGPU && !webGpuAvailable()) {
        opt.disabled = true;
        text += " (WebGPU unavailable)";
      }
      opt.textContent = text;
      sel.appendChild(opt);
    });
    // A ?model= id outside the table is still listed, so the picker shows what is running.
    if (OVERRIDES.model && !findModel(OVERRIDES.model)) {
      var extra = document.createElement("option");
      extra.value = OVERRIDES.model;
      extra.textContent = OVERRIDES.model + " (from URL)";
      extra.dataset.fromUrl = "1";
      sel.appendChild(extra);
    }
    sel.disabled = !sel.options.length;
  }

  // Reflect the effective model in the picker and in the licence notice.
  function syncModelUi() {
    var id = effectiveModel();
    $("#semantic-model").value = id;
    var m = findModel(id);
    var notice = $("#semantic-notice");
    var text = m && m.nonCommercial ? m.notice : "";
    notice.hidden = !text;
    notice.textContent = text;
  }

  // Start-up: cross-check the table, restore the saved choice (the URL override wins for the
  // session and is never saved), and refuse a WebGPU-only model where there is no WebGPU.
  function initModels() {
    MODELS = knownDemoModels();
    var saved = null;
    try { saved = localStorage.getItem(MODEL_KEY); } catch (e) {}
    selectedModel = findModel(saved) ? saved : defaultModelId();
    populateModelSelect();
    var m = findModel(effectiveModel());
    if (m && m.needsWebGPU && !webGpuAvailable()) {
      delete OVERRIDES.model;
      selectedModel = defaultModelId();
      addMessage("info", modelName(m.id) + " needs WebGPU, which this browser doesn’t expose; using " + modelName(selectedModel) + " instead.");
    }
    syncModelUi();
  }

  // From the picker (or ddDemo.setModel): save the choice and, when semantic search is on,
  // restart it on the new model. Returns false for an id the picker doesn't offer.
  function setModel(id) {
    if (!findModel(id)) return false;
    delete OVERRIDES.model; // an explicit choice replaces the session override
    var extra = $("#semantic-model option[data-from-url]");
    if (extra) extra.remove();
    selectedModel = id;
    try { localStorage.setItem(MODEL_KEY, id); } catch (e) {}
    syncModelUi();
    if ($("#semantic").checked) {
      applySemantic(false); // drop the old worker and index; the table goes keyword-only meanwhile
      setSemantic(true);    // new generation: whatever the old start still resolves is ignored
    }
    return true;
  }

  // --- Semantic search: embedder ------------------------------------------
  function loadTransformers() {
    // ?nogpu=1 (test hook): hide WebGPU before Transformers.js probes for it.
    if (OVERRIDES.nogpu) { try { delete Navigator.prototype.gpu; } catch (e) {} }
    return import(TRANSFORMERS_URL).then(function (transformers) {
      transformers.env.allowLocalModels = false;
      return transformers;
    });
  }

  // Embedder options for the main-thread fallback: the effective model, "auto" device unless
  // overridden (WebGPU when present, else WASM), and the library's own dtype choice unless overridden.
  function embedderOptions() {
    var opts = { model: effectiveModel(), device: OVERRIDES.device || "auto" };
    if (OVERRIDES.dtype) opts.dtype = OVERRIDES.dtype;
    return opts;
  }

  // Worker URL: the deploy's ?v=<commit> first, then the configuration as query params
  // (embed-worker.js reads model/device/dtype/nogpu from self.location.search). One worker per model.
  function workerUrl() {
    var params = [
      "model=" + encodeURIComponent(effectiveModel()),
      "device=" + encodeURIComponent(OVERRIDES.device || "auto")
    ];
    if (OVERRIDES.dtype) params.push("dtype=" + encodeURIComponent(OVERRIDES.dtype));
    if (OVERRIDES.nogpu) params.push("nogpu=1");
    return "embed-worker.js" + (ASSET_QUERY ? ASSET_QUERY + "&" : "?") + params.join("&");
  }

  // Start a worker for the current model. Resolves with its embedder proxy once the worker has
  // described itself. The worker is tracked from creation, so stopping semantic search (or
  // switching models) while it is still starting terminates it right away; a start that was
  // superseded (generation moved on) terminates its worker itself when it finally resolves.
  function createWorkerEmbedder(myGen) {
    var worker;
    try { worker = new Worker(workerUrl()); } catch (err) { return Promise.reject(err); }
    semanticWorker = worker;
    return new Promise(function (resolve, reject) {
      var timer = setTimeout(function () { reject(new Error("worker did not respond")); }, 8000);
      worker.addEventListener("error", function (e) {
        clearTimeout(timer);
        reject(new Error(e.message || "worker failed to start"));
      });
      API.createWorkerEmbedder(worker).then(
        function (embedder) { clearTimeout(timer); resolve(embedder); },
        function (err) { clearTimeout(timer); reject(err); }
      );
    }).then(
      function (embedder) {
        if (myGen !== generation) { worker.terminate(); throw new Error("superseded"); }
        return embedder;
      },
      function (err) {
        worker.terminate();
        if (semanticWorker === worker) semanticWorker = null; // the main-thread fallback takes over
        throw err;
      }
    );
  }

  // The loaded embedder for the current start: the worker, else the main thread. The model is
  // downloaded and initialised here (progress + device chip), so the component's own load()
  // call afterwards is a no-op.
  function getEmbedder(myGen) {
    if (embedderPromise) return embedderPromise;
    var canWorker = typeof Worker !== "undefined" && location.protocol !== "file:";
    embedderPromise = (canWorker ? createWorkerEmbedder(myGen) : Promise.reject(new Error("workers unavailable")))
      .catch(function (err) {
        if (myGen !== generation) throw err; // superseded: don't start a main-thread model for it
        // Fallback: run the model on the main thread (also the file:// path).
        return API.createTransformersEmbedder(loadTransformers, embedderOptions());
      })
      .then(function (embedder) {
        if (myGen !== generation) throw new Error("superseded");
        var onProgress = function (fraction) {
          if (myGen === generation) showSemanticStatus({ state: "loading", progress: fraction });
        };
        return Promise.resolve(embedder.load ? embedder.load(onProgress) : undefined)
          .then(function () { return embedder; });
      });
    return embedderPromise;
  }

  // --- Semantic search: status, device chip, ETA ---------------------------
  function setStatusText(text) {
    var el = $("#semantic-status");
    el.hidden = !text;
    el.textContent = text || "";
  }

  function showSemanticStatus(status) {
    if (!status) { eta = null; setStatusText(""); return; }
    if (status.state === "loading") {
      setStatusText(status.progress == null ? "Loading model…" : "Loading model… " + Math.round(status.progress * 100) + "%");
    } else if (status.state === "indexing") {
      setStatusText("Indexing… " + fmtCount(status.done) + " / " + fmtCount(status.total) + indexingEta(status));
    } else if (status.state === "ready") {
      eta = null;
      setStatusText(""); // the component's own chip ("Semantic search on") takes over from here
    } else {
      eta = null;
      setStatusText("Unavailable: " + status.message);
    }
  }

  // " · ≈ 2 min left" once ≥ 2 s and ≥ 32 texts have passed since this run's first sample.
  function indexingEta(status) {
    var now = performance.now();
    if (!eta) { eta = { t0: now, done0: status.done }; return ""; }
    var elapsed = now - eta.t0;
    var embedded = status.done - eta.done0;
    if (elapsed < 2000 || embedded < 32 || status.done >= status.total) return "";
    return " · ≈ " + fmtDuration((status.total - status.done) * elapsed / embedded) + " left";
  }

  function fmtCount(n) { return Number(n).toLocaleString(); }

  function fmtDuration(ms) {
    var s = Math.max(1, Math.round(ms / 1000));
    if (s < 60) return s + " s";
    var min = Math.round(s / 60);
    if (min < 60) return min + " min";
    var h = Math.floor(min / 60);
    return h + " h " + (min - h * 60) + " min";
  }

  var DEVICE_LABELS = { webgpu: "WebGPU", wasm: "WASM", cpu: "CPU" };

  // "WebGPU · fp16" / "WASM · q8" from embedder.info (known once load() is done).
  function showDeviceInfo(info) {
    var el = $("#semantic-device");
    if (!info || !info.device) {
      el.hidden = true;
      el.textContent = "";
      el.removeAttribute("data-device");
      el.removeAttribute("title");
      return;
    }
    var device = String(info.device).toLowerCase();
    var parts = [DEVICE_LABELS[device] || info.device];
    if (info.dtype) parts.push(info.dtype);
    el.textContent = parts.join(" · ");
    el.setAttribute("data-device", device);
    el.title = info.model || effectiveModel();
    el.hidden = false;
  }

  // --- Semantic search: precomputed vectors ---------------------------------
  // build-presets.mjs attaches `vectors` ([{ model, file, bytes, spaceId }]) to a preset when
  // scripts/build-vectors.mjs has produced a snapshot for it. The entry for the running model is
  // fetched once per session and handed to the component as `semanticSearch.snapshot`, so the
  // dictionary is searchable without embedding anything in the browser. Never over file://
  // (fetch is blocked there).
  function snapshotEntry() {
    var p = docsFromPreset ? activePreset : null;
    if (!p || !p.vectors || location.protocol === "file:") return null;
    var model = effectiveModel();
    for (var i = 0; i < p.vectors.length; i++) if (p.vectors[i].model === model) return p.vectors[i];
    return null;
  }

  // Fetch + decode one vectors file (memoised). Failures are logged and leave `value` null.
  function loadSnapshot(entry) {
    var slot = snapshots[entry.file];
    if (slot) return slot;
    slot = snapshots[entry.file] = { promise: null, done: false, value: null, waiting: false };
    slot.promise = fetch(entry.file + ASSET_QUERY)
      .then(function (r) {
        if (!r.ok) throw new Error("HTTP " + r.status);
        return r.arrayBuffer();
      })
      .then(function (bytes) {
        if (typeof API.decodeVectorSnapshot !== "function") throw new Error("this build has no decodeVectorSnapshot()");
        slot.value = API.decodeVectorSnapshot(bytes);
      })
      .catch(function (err) {
        console.info("[demo] Precomputed vectors unavailable (" + entry.file + ": " + ((err && err.message) || err) + "); embedding in the browser instead.");
        slot.value = null;
      })
      .then(function () { slot.done = true; return slot.value; });
    return slot;
  }

  // semanticSearch options for this render: null while semantic search is off, or while the
  // preset's precomputed vectors are still downloading (the render goes keyword-only for now
  // and repeats once they land, so the index never starts embedding what the file provides).
  function semanticOptions() {
    if (!semanticEmbedder) return null;
    var entry = snapshotEntry();
    var slot = entry ? loadSnapshot(entry) : null;
    if (slot && !slot.done) {
      lastSnapshot = null;
      setStatusText("Loading precomputed vectors…");
      if (!slot.waiting) {
        slot.waiting = true;
        slot.promise.then(function () {
          slot.waiting = false;
          if (semanticEmbedder && snapshotEntry() === entry) render();
        });
      }
      return null;
    }
    eta = null; // this render starts a new indexing run
    lastSnapshot = slot ? slot.value : null;
    var opts = { embedder: semanticEmbedder, onStatus: showSemanticStatus };
    if (lastSnapshot) opts.snapshot = lastSnapshot;
    return opts;
  }

  // --- Semantic search: start / stop ---------------------------------------
  // From the checkbox: remember the choice, then apply it.
  function setSemantic(on) {
    try { localStorage.setItem(SEMANTIC_KEY, on ? "1" : "0"); } catch (e) {}
    applySemantic(on);
  }

  // Start or stop semantic search without touching the saved preference (start-up, ?semantic=).
  function applySemantic(on) {
    if (!on) {
      stopSemantic();
      render();
      return;
    }
    var myGen = ++generation;
    eta = null;
    $("#semantic-hint").hidden = false;
    showSemanticStatus({ state: "loading", progress: undefined });
    var entry = snapshotEntry();
    var vectors = entry ? loadSnapshot(entry).promise : Promise.resolve(null); // alongside the model download
    Promise.all([getEmbedder(myGen), vectors]).then(
      function (values) {
        if (myGen !== generation || !$("#semantic").checked) return; // restarted or unticked while starting
        semanticEmbedder = values[0];
        showDeviceInfo(semanticEmbedder.info);
        render();
      },
      function (err) {
        if (myGen !== generation) return; // a newer start owns the UI
        stopSemantic();
        $("#semantic").checked = false;
        addMessage("error", "Couldn’t start semantic search: " + err.message);
      }
    );
  }

  // Drop the embedder (and its worker) and clear the semantic UI; the next start recreates them.
  function stopSemantic() {
    semanticEmbedder = null;
    embedderPromise = null;
    lastSnapshot = null;
    eta = null;
    if (semanticWorker) { semanticWorker.terminate(); semanticWorker = null; }
    showSemanticStatus(null);
    showDeviceInfo(null);
    $("#semantic-hint").hidden = true;
  }

  // --- Export -------------------------------------------------------------
  function slug(s) {
    return (String(s || "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "")) || "data-dictionary";
  }

  function escapeHtml(s) {
    return String(s).replace(/[&<>"]/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;" }[c];
    });
  }

  function downloadBlob(filename, type, content) {
    var blob = new Blob([content], { type: type });
    var url = URL.createObjectURL(blob);
    var a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    a.remove();
    setTimeout(function () { URL.revokeObjectURL(url); }, 1000);
  }

  function downloadHtml() {
    if (!lastTable) return;
    var widget = API.tableToHtml(lastTable, { theme: $("#theme").value });
    var page =
      "<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n" +
      "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n" +
      "<title>" + escapeHtml(lastTable.title || "Data dictionary") + "</title>\n" +
      "<style>body{margin:0;padding:24px;max-width:1200px;margin-inline:auto;background:#fafbfc;}</style>\n" +
      "</head>\n<body>\n" + widget + "\n</body>\n</html>\n";
    downloadBlob(slug(lastTable.title) + ".html", "text/html;charset=utf-8", page);
  }

  function downloadCsv() {
    if (!lastTable) return;
    downloadBlob(slug(lastTable.title) + ".csv", "text/csv;charset=utf-8", API.tableToCsv(lastTable));
  }

  // Build a formatted .xlsx with ExcelJS: a leading Category column plus the seven
  // standard columns, a bold frozen header, auto-filter, sized columns and wrapped
  // long-text cells. Complex columns are stringified by toPlainRows into one cell each.
  var XLSX_COLUMNS = ["Category", "Variable name", "Description", "Data type", "Format", "Valid values", "Constraints", "Additional information"];
  var XLSX_WIDTHS = { "Category": 18, "Variable name": 26, "Description": 48, "Data type": 16, "Format": 18, "Valid values": 40, "Constraints": 32, "Additional information": 30 };
  var XLSX_WRAP = { "Description": 1, "Format": 1, "Valid values": 1, "Constraints": 1, "Additional information": 1 };

  function downloadExcel() {
    if (!lastTable || !window.ExcelJS) return;

    // includeInternalColumns adds the "Category" (and an unused "Source") field.
    var plain = API.toPlainRows(lastTable, { includeInternalColumns: true });

    var wb = new ExcelJS.Workbook();
    var ws = wb.addWorksheet("Data dictionary", { views: [{ state: "frozen", ySplit: 1 }] });
    ws.columns = XLSX_COLUMNS.map(function (c) {
      return { header: c, key: c, width: XLSX_WIDTHS[c], style: { alignment: { vertical: "top", wrapText: !!XLSX_WRAP[c] } } };
    });

    // Header row: bold white text on a dark fill.
    var head = ws.getRow(1);
    head.font = { bold: true, color: { argb: "FFFFFFFF" } };
    head.alignment = { vertical: "middle", wrapText: true };
    head.eachCell(function (cell) {
      cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF1F4E79" } };
    });

    plain.forEach(function (r) {
      var record = {};
      XLSX_COLUMNS.forEach(function (c) { record[c] = r[c] != null ? r[c] : ""; });
      ws.addRow(record);
    });

    ws.autoFilter = { from: { row: 1, column: 1 }, to: { row: 1, column: XLSX_COLUMNS.length } };

    wb.xlsx.writeBuffer().then(
      function (buf) {
        downloadBlob(slug(lastTable.title) + ".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", buf);
      },
      function (err) { addMessage("error", "Couldn’t build the Excel file: " + err.message); }
    );
  }

  // --- Input panel collapse ----------------------------------------------
  // Hide the upload sidebar so the table reclaims its grid column. The toggle lives
  // in the always-rendered output toolbar, so it stays reachable once the panel is gone.
  var INPUTS_COLLAPSED_KEY = "dd-demo:inputs-collapsed";

  function setInputsCollapsed(collapsed) {
    $("#layout").classList.toggle("inputs-collapsed", collapsed);
    var btn = $("#toggle-input-btn");
    btn.setAttribute("aria-expanded", String(!collapsed));
    btn.title = collapsed ? "Show input panel" : "Hide input panel";
    $(".panel-toggle-icon").textContent = collapsed ? "›" : "‹";
    $(".panel-toggle-label").textContent = collapsed ? "Show panel" : "Hide panel";
    try { localStorage.setItem(INPUTS_COLLAPSED_KEY, collapsed ? "1" : "0"); } catch (e) {}
  }

  // --- Wiring -------------------------------------------------------------
  function wire() {
    $("#preset-select").addEventListener("change", function (e) { loadPreset(e.target.value); });

    $("#file-input").addEventListener("change", function (e) { addFiles(e.target.files); e.target.value = ""; });
    $("#folder-input").addEventListener("change", function (e) { addFiles(e.target.files); e.target.value = ""; });

    var dz = $("#drop-zone");
    ["dragenter", "dragover"].forEach(function (ev) {
      dz.addEventListener(ev, function (e) { e.preventDefault(); dz.classList.add("dragover"); });
    });
    ["dragleave", "dragend"].forEach(function (ev) {
      dz.addEventListener(ev, function () { dz.classList.remove("dragover"); });
    });
    dz.addEventListener("drop", function (e) {
      e.preventDefault();
      dz.classList.remove("dragover");
      handleDrop(e);
    });

    $("#doc-list").addEventListener("click", function (e) {
      var btn = e.target.closest("button[data-index]");
      if (btn) removeDoc(Number(btn.dataset.index));
    });
    $("#clear-btn").addEventListener("click", clearAll);

    $("#root-select").addEventListener("change", function (e) {
      rootIndex = e.target.value === "" ? null : Number(e.target.value);
      render();
    });
    ["#theme", "#expand-categories", "#expand-additional"].forEach(function (sel) {
      $(sel).addEventListener("change", function () { render(); });
    });
    $("#shadow").addEventListener("change", function () { delete OVERRIDES.shadow; render(); });
    $("#semantic").addEventListener("change", function (e) { setSemantic(e.target.checked); });
    $("#semantic-model").addEventListener("change", function (e) {
      if (!setModel(e.target.value)) syncModelUi(); // unusable choice: snap back to what runs
    });

    $("#download-html-btn").addEventListener("click", downloadHtml);
    $("#download-csv-btn").addEventListener("click", downloadCsv);
    $("#download-excel-btn").addEventListener("click", downloadExcel);

    $("#toggle-input-btn").addEventListener("click", function () {
      setInputsCollapsed(!$("#layout").classList.contains("inputs-collapsed"));
    });
  }

  // --- URL overrides ------------------------------------------------------
  // Session-only knobs for automation and benchmarking, read once at start-up and never
  // persisted:
  //   ?preset=<key|index>      load this preset instead of the first one (e.g. bcrpp)
  //   ?semantic=1|0            force the semantic toggle on/off, ignoring the saved preference
  //   ?model=<id>              embedding model id (wins over the picker's saved choice; not saved)
  //   ?device=auto|wasm|webgpu execution device (default auto; forwarded to the worker)
  //   ?dtype=<string>          model quantisation, e.g. q8 / fp16 (default: the library's per-device choice)
  //   ?nogpu=1                 hide WebGPU from Transformers.js (exercises the WASM path)
  //   ?shadow=0                render into light DOM ({ shadow: false })
  function readOverrides() {
    var o = {};
    var params;
    try { params = new URLSearchParams(location.search); } catch (e) { return o; }
    var flag = function (name) {
      var v = params.get(name);
      return v === "1" ? true : v === "0" ? false : undefined;
    };
    if (params.get("preset")) o.preset = params.get("preset");
    if (flag("semantic") !== undefined) o.semantic = flag("semantic");
    ["model", "device", "dtype"].forEach(function (k) { if (params.get(k)) o[k] = params.get(k); });
    if (flag("nogpu") === true) o.nogpu = true;
    if (flag("shadow") === false) o.shadow = false;
    return o;
  }

  // --- Automation hooks ---------------------------------------------------
  // Stable handles for scripted checks and benchmarks.
  window.ddDemo = {
    presets: allPresets,
    loadPreset: loadPreset,
    render: function () { render(); },
    element: function () { return $("#output").firstElementChild; }, // the mounted <json-data-dictionary>
    embedder: function () { return semanticEmbedder; },
    worker: function () { return semanticWorker; },
    models: function () { return MODELS.slice(); },   // picker entries (after the library cross-check)
    model: effectiveModel,                            // effective embedding model id
    setModel: setModel,                               // pick a model; restarts semantic search when on
    snapshot: function () { return lastSnapshot; },   // decoded precomputed vectors in use, or null
    lastTable: function () { return lastTable; },
    get lastRenderMs() { return lastRenderMs; }
  };

  // --- Bootstrap ----------------------------------------------------------
  function start() {
    if (!API) {
      var banner = $("#missing-bundle");
      if (banner) banner.hidden = false;
      return;
    }
    OVERRIDES = readOverrides();
    populatePresetSelect();
    wire();
    if (OVERRIDES.shadow === false) $("#shadow").checked = false;

    var savedCollapsed = null;
    try { savedCollapsed = localStorage.getItem(INPUTS_COLLAPSED_KEY); } catch (e) {}
    if (savedCollapsed === "1") setInputsCollapsed(true);

    if (allPresets().length) {
      var initial = OVERRIDES.preset != null ? findPresetIndex(OVERRIDES.preset) : 0;
      loadPreset(initial >= 0 ? initial : 0);
      if (initial < 0) addMessage("warning", "Unknown preset “" + OVERRIDES.preset + "” in the URL; loaded the first example instead.");
    } else {
      render(); // show the empty-state prompt
    }

    // The model picker needs to know whether WebGPU is usable (a few ms), so it is built once
    // the probe answers; semantic search then starts from the saved preference / URL override.
    probeWebGpu().then(function (available) {
      WEBGPU = available;
      initModels(); // after the first render: its clearMessages() would wipe the "needs WebGPU" note

      var savedSemantic = null;
      try { savedSemantic = localStorage.getItem(SEMANTIC_KEY); } catch (e) {}
      var wantSemantic = OVERRIDES.semantic !== undefined ? OVERRIDES.semantic : savedSemantic === "1";
      if (wantSemantic) {
        $("#semantic").checked = true;
        applySemantic(true); // not persisted: a ?semantic=1 visit must not change the saved preference
      }
    });
  }

  start();
})();
