/*
 * Demo app for json-schema-data-dictionary.
 *
 * No schema editor: users either pick a built-in preset (window.DEMO_PRESETS,
 * generated from tests/fixtures by build-presets.mjs, plus one 10,000-variable
 * stress-test preset synthesised in the browser) or upload their own .json
 * files / folders. Each document is handed to the library as { uri, name, schema }
 * with a synthetic uri of https://demo.local/<path> so that relative $refs between
 * documents resolve exactly as they would on disk.
 *
 * Automation hooks: session-only URL overrides (see readOverrides) and window.ddDemo.
 */
(function () {
  "use strict";

  var API = window.JsonSchemaDataDictionary;
  var SYNTH_BASE = "https://demo.local/";

  var $ = function (sel) { return document.querySelector(sel); };

  // --- State --------------------------------------------------------------
  var docs = [];            // [{ path, schema }]
  var rootIndex = null;     // null = auto-detect; number = explicit root document
  var docsFromPreset = false;
  var syntheticTimes = 0;   // > 0 while the synthetic stress-test preset is loaded: cloneTable() factor
  var lastTable = null;
  var lastRenderMs = null;  // wall time of the last renderDataDictionary() call (window.ddDemo.lastRenderMs)

  // Session-only URL overrides (see readOverrides), populated once in start().
  var OVERRIDES = {};

  // Semantic search (opt-in). The model runs in demo/embed-worker.js when Workers are
  // available (not on file://), otherwise on the main thread. The embedder is created once
  // and reused across re-renders; the library caches row embeddings in IndexedDB.
  var SEMANTIC_KEY = "dd-demo:semantic";
  var TRANSFORMERS_URL = "https://cdn.jsdelivr.net/npm/@huggingface/transformers@4.2.0";
  // The Pages deploy appends ?v=<commit> to every asset URL (cache-busting). Forward it to
  // the worker so a fresh app.js never pairs with a stale embed-worker.js.
  var ASSET_QUERY = (function () {
    try {
      var src = document.currentScript && document.currentScript.src;
      var m = src && /\?v=[^&#]+/.exec(src);
      return m ? m[0] : "";
    } catch (e) { return ""; }
  })();
  var EMBEDDING_MODEL = "Xenova/bge-small-en-v1.5";
  var semanticEmbedder = null;   // set once the embedder is ready and the box is still ticked
  var semanticWorker = null;
  var embedderPromise = null;

  // --- Messages -----------------------------------------------------------
  function clearMessages() { $("#messages").replaceChildren(); }
  function addMessage(type, text) {
    var div = document.createElement("div");
    div.className = "message " + type;
    div.textContent = text;
    $("#messages").appendChild(div);
  }

  // --- Presets ------------------------------------------------------------
  // Built-in presets come from presets.js (generated by build-presets.mjs, each with a stable
  // `key`). One more is synthesised in the browser: the BCRPP dictionary cloned 95× as a
  // 10,000-variable stress test (`from` names the source preset by key, `times` the factor).
  var SYNTHETIC_PRESET = {
    key: "synthetic10k",
    label: "Synthetic — 10,000 variables (stress test)",
    description:
      "The BCRPP dictionary cloned 95× with suffixed variable names: 10,070 rows in 1,045 categories, built in the browser. " +
      "Semantic indexing takes about a minute on WebGPU and 20+ minutes on WASM.",
    from: "bcrpp",
    times: 95
  };

  function allPresets() {
    var presets = (window.DEMO_PRESETS || []).slice();
    if (findByKey(presets, SYNTHETIC_PRESET.from)) presets.push(SYNTHETIC_PRESET);
    return presets;
  }

  function findByKey(presets, key) {
    for (var i = 0; i < presets.length; i++) if (presets[i].key === key) return presets[i];
    return null;
  }

  // Resolve a preset key or index (number or numeric string) to an index into allPresets(); -1 if unknown.
  function findPresetIndex(indexOrKey) {
    var presets = allPresets();
    var s = String(indexOrKey);
    for (var i = 0; i < presets.length; i++) if (presets[i].key === s) return i;
    if (/^\d+$/.test(s) && Number(s) < presets.length) return Number(s);
    return -1;
  }

  function presetValue(p, i) { return p.key || String(i); }

  function populatePresetSelect() {
    var sel = $("#preset-select");
    var presets = allPresets();
    sel.replaceChildren();
    if (!presets.length) {
      var o = document.createElement("option");
      o.textContent = "(no examples available — run npm run demo)";
      sel.appendChild(o);
      sel.disabled = true;
      return;
    }
    presets.forEach(function (p, i) {
      var opt = document.createElement("option");
      opt.value = presetValue(p, i);
      opt.textContent = p.label;
      sel.appendChild(opt);
    });
  }

  // Load a preset by key ("bcrpp", "synthetic10k") or index. Returns false when unknown.
  function loadPreset(indexOrKey) {
    var presets = allPresets();
    var i = findPresetIndex(indexOrKey);
    var p = presets[i];
    if (!p) return false;
    var source = p.from ? findByKey(presets, p.from) : p;
    if (!source) return false;
    $("#preset-select").value = presetValue(p, i);
    $("#preset-description").textContent = p.description || "";
    docs = source.documents.map(function (d) { return { path: d.path, schema: d.schema }; });
    docsFromPreset = true;
    syntheticTimes = p.times || 0;
    rootIndex = null;
    afterDocsChanged();
    return true;
  }

  // Stress-test helper: `base` repeated `times` times. Copy k gets its own row objects (variable
  // names suffixed `_k`) and categories (id `-k`, title `· copy k`). Each row object is shared
  // between `rows` and its category — the library matches rows by identity — and `__category`
  // follows the cloned title so the CSV/Excel exports stay consistent.
  function cloneTable(base, times) {
    var rows = [];
    var categories = [];
    for (var k = 1; k <= times; k++) appendClone(base, k, rows, categories);
    return {
      title: (base.title || "Data dictionary") + " (synthetic ×" + times + ")",
      description: base.description,
      comment: base.comment,
      rows: rows,
      categories: categories,
      conditionalRules: base.conditionalRules,
      additionalInformation: base.additionalInformation,
      warnings: base.warnings,
      source: base.source
    };
  }

  function appendClone(base, k, rows, categories) {
    var copies = new Map(); // base row -> its clone in copy k
    base.rows.forEach(function (row) {
      var copy = cloneRow(row, k);
      copies.set(row, copy);
      rows.push(copy);
    });
    base.categories.forEach(function (cat) {
      var title = cat.title + " · copy " + k;
      var catRows = cat.rows.map(function (row) {
        var copy = copies.get(row) || cloneRow(row, k); // a row outside base.rows stays outside
        if (copy.__category != null) copy.__category = title;
        return copy;
      });
      categories.push(Object.assign({}, cat, { id: cat.id + "-" + k, title: title, rows: catRows }));
    });
  }

  function cloneRow(row, k) {
    var copy = Object.assign({}, row);
    copy["Variable name"] = row["Variable name"] + "_" + k;
    return copy;
  }

  // --- File / folder ingestion -------------------------------------------
  // Folder uploads (webkitdirectory / dropped directories) prefix every path with
  // the chosen folder's name. Strip that single common top segment so paths line up
  // with the relative $refs (e.g. "myset/categories/x.json" -> "categories/x.json").
  function stripCommonTopFolder(paths) {
    if (!paths.length) return paths;
    var i = paths[0].indexOf("/");
    var top = i === -1 ? paths[0] : paths[0].slice(0, i);
    var everyUnderTop = paths.every(function (p) { return p.indexOf(top + "/") === 0; });
    return everyUnderTop ? paths.map(function (p) { return p.slice(top.length + 1); }) : paths;
  }

  function isJson(name) { return /\.json$/i.test(name); }

  // Read + parse a list of { path, file } items, then merge into `docs`.
  function ingest(items) {
    if (!items.length) {
      clearMessages();
      addMessage("error", "No .json files found in that selection.");
      return Promise.resolve();
    }
    var paths = stripCommonTopFolder(items.map(function (it) { return it.path; }));
    var errors = [];
    var reads = items.map(function (it, k) {
      var path = paths[k];
      return it.file.text().then(
        function (text) {
          try { return { path: path, schema: JSON.parse(text) }; }
          catch (err) {
            errors.push({ type: "error", text: "JSON parse error in “" + path + "”: " + err.message });
            return null;
          }
        },
        function () {
          errors.push({ type: "error", text: "Could not read “" + path + "”." });
          return null;
        }
      );
    });

    return Promise.all(reads).then(function (results) {
      var parsed = results.filter(Boolean);
      if (!parsed.length) {
        clearMessages();
        errors.forEach(function (e) { addMessage(e.type, e.text); });
        return;
      }
      // Uploading replaces a preset, but multiple uploads accumulate into one set.
      if (docsFromPreset) { docs = []; docsFromPreset = false; }
      syntheticTimes = 0;
      parsed.forEach(function (d) {
        var idx = docs.findIndex(function (x) { return x.path === d.path; });
        if (idx >= 0) docs[idx] = d; else docs.push(d);
      });
      rootIndex = null;
      afterDocsChanged(errors); // surface any per-file parse errors alongside the result
    });
  }

  function addFiles(fileList) {
    var items = Array.prototype.slice.call(fileList)
      .filter(function (f) { return isJson(f.name); })
      .map(function (f) { return { path: f.webkitRelativePath || f.name, file: f }; });
    return ingest(items);
  }

  // Recursively gather files (with relative paths) from a dropped directory entry.
  function walkEntry(entry, prefix, out) {
    return new Promise(function (resolve) {
      if (entry.isFile) {
        entry.file(
          function (file) { out.push({ path: prefix + entry.name, file: file }); resolve(); },
          function () { resolve(); }
        );
      } else if (entry.isDirectory) {
        var reader = entry.createReader();
        var readBatch = function () {
          reader.readEntries(function (batch) {
            if (!batch.length) { resolve(); return; }
            Promise.all(batch.map(function (child) {
              return walkEntry(child, prefix + entry.name + "/", out);
            })).then(readBatch); // readEntries yields in chunks; keep going until empty
          }, function () { resolve(); });
        };
        readBatch();
      } else {
        resolve();
      }
    });
  }

  function handleDrop(e) {
    var dt = e.dataTransfer;
    var entries = [];
    if (dt.items && dt.items.length && dt.items[0].webkitGetAsEntry) {
      // webkitGetAsEntry() must be called synchronously during the drop event.
      entries = Array.prototype.slice.call(dt.items)
        .map(function (it) { return it.webkitGetAsEntry(); })
        .filter(Boolean);
    }
    if (entries.length) {
      var collected = [];
      Promise.all(entries.map(function (entry) { return walkEntry(entry, "", collected); }))
        .then(function () {
          ingest(collected.filter(function (c) { return isJson(c.path); }));
        });
    } else if (dt.files && dt.files.length) {
      addFiles(dt.files);
    }
  }

  // --- Manifest + root selector ------------------------------------------
  function renderDocList() {
    var field = $("#doc-list-field");
    var list = $("#doc-list");
    $("#doc-count").textContent = String(docs.length);
    field.hidden = docs.length === 0;
    list.replaceChildren();
    docs.forEach(function (d, i) {
      var li = document.createElement("li");
      var name = document.createElement("span");
      name.className = "doc-path";
      name.textContent = d.path;
      var btn = document.createElement("button");
      btn.type = "button";
      btn.className = "doc-remove";
      btn.dataset.index = String(i);
      btn.setAttribute("aria-label", "Remove " + d.path);
      btn.textContent = "×";
      li.append(name, btn);
      list.appendChild(li);
    });
  }

  function populateRootSelect() {
    var sel = $("#root-select");
    sel.replaceChildren();
    var auto = document.createElement("option");
    auto.value = "";
    auto.textContent = "Auto-detect";
    sel.appendChild(auto);
    docs.forEach(function (d, i) {
      var o = document.createElement("option");
      o.value = String(i);
      o.textContent = d.path;
      sel.appendChild(o);
    });
    sel.value = rootIndex == null ? "" : String(rootIndex);
  }

  function removeDoc(i) {
    docs.splice(i, 1);
    rootIndex = null; // indices shifted; fall back to auto-detect
    syntheticTimes = 0;
    afterDocsChanged();
  }

  function clearAll() {
    docs = [];
    rootIndex = null;
    docsFromPreset = false;
    syntheticTimes = 0;
    afterDocsChanged();
  }

  // --- Build inputs + render ---------------------------------------------
  function buildInputs() {
    return docs.map(function (d) {
      var path = String(d.path || "document.json").replace(/^\/+/, "");
      return {
        uri: SYNTH_BASE + path,
        name: path.split("/").pop() || "document.json",
        schema: d.schema
      };
    });
  }

  function setExportsEnabled(on) {
    $("#download-html-btn").disabled = !on;
    $("#download-csv-btn").disabled = !on;
    // Excel export also needs the (vendored) ExcelJS global to have loaded.
    $("#download-excel-btn").disabled = !on || !window.ExcelJS;
  }

  function afterDocsChanged(extras) {
    renderDocList();
    populateRootSelect();
    render(extras);
  }

  function render(extras) {
    clearMessages();
    (extras || []).forEach(function (m) { addMessage(m.type, m.text); });

    var out = $("#output");
    if (!docs.length) {
      out.replaceChildren();
      lastTable = null;
      lastRenderMs = null;
      setExportsEnabled(false);
      addMessage("info", "Select an example or upload one or more JSON Schema files to begin.");
      return;
    }

    var table;
    try {
      var opts = rootIndex != null ? { rootIndex: rootIndex } : {};
      table = API.schemaDocumentsToTable(buildInputs(), opts);
      if (syntheticTimes > 0) table = cloneTable(table, syntheticTimes);
    } catch (err) {
      out.replaceChildren();
      lastTable = null;
      lastRenderMs = null;
      setExportsEnabled(false);
      addMessage("error", "Couldn’t build the data dictionary: " + err.message);
      return;
    }

    lastTable = table;
    (table.warnings || []).forEach(function (w) { addMessage("warning", w); });

    var options = {
      // ?shadow=0 forces light DOM until the checkbox is touched (see wire()).
      shadow: OVERRIDES.shadow === false ? false : $("#shadow").checked,
      theme: $("#theme").value,
      expandCategories: $("#expand-categories").checked,
      expandAdditionalInfo: $("#expand-additional").checked
    };
    if (semanticEmbedder) options.semanticSearch = { embedder: semanticEmbedder, onStatus: showSemanticStatus };
    var t0 = performance.now();
    API.renderDataDictionary(out, table, options); // renders synchronously; painting is extra
    lastRenderMs = performance.now() - t0;
    setExportsEnabled(true);
  }

  // --- Semantic search ----------------------------------------------------
  function loadTransformers() {
    // ?nogpu=1 (test hook): hide WebGPU before Transformers.js probes for it.
    if (OVERRIDES.nogpu) { try { delete Navigator.prototype.gpu; } catch (e) {} }
    return import(TRANSFORMERS_URL).then(function (transformers) {
      transformers.env.allowLocalModels = false;
      return transformers;
    });
  }

  // Embedder options for the main-thread fallback: the URL overrides, else the library defaults.
  function embedderOptions() {
    var opts = { model: OVERRIDES.model || EMBEDDING_MODEL };
    if (OVERRIDES.device) opts.device = OVERRIDES.device;
    if (OVERRIDES.dtype) opts.dtype = OVERRIDES.dtype;
    return opts;
  }

  // Worker URL: the deploy's ?v=<commit> first, then the session overrides as query params
  // (embed-worker.js reads model/device/dtype/nogpu from self.location.search).
  function workerUrl() {
    var params = [];
    ["model", "device", "dtype"].forEach(function (k) {
      if (OVERRIDES[k]) params.push(k + "=" + encodeURIComponent(OVERRIDES[k]));
    });
    if (OVERRIDES.nogpu) params.push("nogpu=1");
    if (!params.length) return "embed-worker.js" + ASSET_QUERY;
    return "embed-worker.js" + (ASSET_QUERY ? ASSET_QUERY + "&" : "?") + params.join("&");
  }

  function createWorkerEmbedder() {
    return new Promise(function (resolve, reject) {
      var worker;
      try { worker = new Worker(workerUrl()); } catch (err) { reject(err); return; }
      var timer = setTimeout(function () { reject(new Error("worker did not respond")); }, 8000);
      worker.addEventListener("error", function (e) {
        clearTimeout(timer);
        reject(new Error(e.message || "worker failed to start"));
      });
      API.createWorkerEmbedder(worker).then(
        function (embedder) { clearTimeout(timer); semanticWorker = worker; resolve(embedder); },
        function (err) { clearTimeout(timer); reject(err); }
      );
    }).catch(function (err) {
      if (semanticWorker) { semanticWorker.terminate(); semanticWorker = null; }
      throw err;
    });
  }

  function getEmbedder() {
    if (embedderPromise) return embedderPromise;
    var canWorker = typeof Worker !== "undefined" && location.protocol !== "file:";
    embedderPromise = (canWorker ? createWorkerEmbedder() : Promise.reject(new Error("workers unavailable")))
      .catch(function () {
        // Fallback: run the model on the main thread (also the file:// path).
        return API.createTransformersEmbedder(loadTransformers, embedderOptions());
      });
    return embedderPromise;
  }

  function showSemanticStatus(status) {
    var el = $("#semantic-status");
    if (!status) { el.hidden = true; el.textContent = ""; return; }
    el.hidden = false;
    if (status.state === "loading") {
      el.textContent = status.progress == null ? "Loading model…" : "Loading model… " + Math.round(status.progress * 100) + "%";
    } else if (status.state === "indexing") {
      el.textContent = "Indexing variables… " + status.done + " / " + status.total;
    } else if (status.state === "ready") {
      // The component's own chip ("Semantic search on") takes over from here.
      el.hidden = true;
      el.textContent = "";
    } else {
      el.textContent = "Unavailable: " + status.message;
    }
  }

  // From the checkbox: remember the choice, then apply it.
  function setSemantic(on) {
    try { localStorage.setItem(SEMANTIC_KEY, on ? "1" : "0"); } catch (e) {}
    applySemantic(on);
  }

  // Start or stop semantic search without touching the saved preference (start-up, ?semantic=).
  function applySemantic(on) {
    if (!on) {
      semanticEmbedder = null;
      embedderPromise = null;
      if (semanticWorker) { semanticWorker.terminate(); semanticWorker = null; }
      showSemanticStatus(null);
      render();
      return;
    }
    showSemanticStatus({ state: "loading", progress: undefined });
    getEmbedder().then(
      function (embedder) {
        if (!$("#semantic").checked) return; // unticked while starting
        semanticEmbedder = embedder;
        render();
      },
      function (err) {
        embedderPromise = null;
        $("#semantic").checked = false;
        showSemanticStatus(null);
        addMessage("error", "Couldn’t start semantic search: " + err.message);
      }
    );
  }

  // --- Export -------------------------------------------------------------
  function slug(s) {
    return (String(s || "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "")) || "data-dictionary";
  }

  function escapeHtml(s) {
    return String(s).replace(/[&<>"]/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;" }[c];
    });
  }

  function downloadBlob(filename, type, content) {
    var blob = new Blob([content], { type: type });
    var url = URL.createObjectURL(blob);
    var a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    a.remove();
    setTimeout(function () { URL.revokeObjectURL(url); }, 1000);
  }

  function downloadHtml() {
    if (!lastTable) return;
    var widget = API.tableToHtml(lastTable, { theme: $("#theme").value });
    var page =
      "<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n" +
      "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n" +
      "<title>" + escapeHtml(lastTable.title || "Data dictionary") + "</title>\n" +
      "<style>body{margin:0;padding:24px;max-width:1200px;margin-inline:auto;background:#fafbfc;}</style>\n" +
      "</head>\n<body>\n" + widget + "\n</body>\n</html>\n";
    downloadBlob(slug(lastTable.title) + ".html", "text/html;charset=utf-8", page);
  }

  function downloadCsv() {
    if (!lastTable) return;
    downloadBlob(slug(lastTable.title) + ".csv", "text/csv;charset=utf-8", API.tableToCsv(lastTable));
  }

  // Build a formatted .xlsx with ExcelJS: a leading Category column plus the seven
  // standard columns, a bold frozen header, auto-filter, sized columns and wrapped
  // long-text cells. Complex columns are stringified by toPlainRows into one cell each.
  var XLSX_COLUMNS = ["Category", "Variable name", "Description", "Data type", "Format", "Valid values", "Constraints", "Additional information"];
  var XLSX_WIDTHS = { "Category": 18, "Variable name": 26, "Description": 48, "Data type": 16, "Format": 18, "Valid values": 40, "Constraints": 32, "Additional information": 30 };
  var XLSX_WRAP = { "Description": 1, "Format": 1, "Valid values": 1, "Constraints": 1, "Additional information": 1 };

  function downloadExcel() {
    if (!lastTable || !window.ExcelJS) return;

    // includeInternalColumns adds the "Category" (and an unused "Source") field.
    var plain = API.toPlainRows(lastTable, { includeInternalColumns: true });

    var wb = new ExcelJS.Workbook();
    var ws = wb.addWorksheet("Data dictionary", { views: [{ state: "frozen", ySplit: 1 }] });
    ws.columns = XLSX_COLUMNS.map(function (c) {
      return { header: c, key: c, width: XLSX_WIDTHS[c], style: { alignment: { vertical: "top", wrapText: !!XLSX_WRAP[c] } } };
    });

    // Header row: bold white text on a dark fill.
    var head = ws.getRow(1);
    head.font = { bold: true, color: { argb: "FFFFFFFF" } };
    head.alignment = { vertical: "middle", wrapText: true };
    head.eachCell(function (cell) {
      cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF1F4E79" } };
    });

    plain.forEach(function (r) {
      var record = {};
      XLSX_COLUMNS.forEach(function (c) { record[c] = r[c] != null ? r[c] : ""; });
      ws.addRow(record);
    });

    ws.autoFilter = { from: { row: 1, column: 1 }, to: { row: 1, column: XLSX_COLUMNS.length } };

    wb.xlsx.writeBuffer().then(
      function (buf) {
        downloadBlob(slug(lastTable.title) + ".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", buf);
      },
      function (err) { addMessage("error", "Couldn’t build the Excel file: " + err.message); }
    );
  }

  // --- Input panel collapse ----------------------------------------------
  // Hide the upload sidebar so the table reclaims its grid column. The toggle lives
  // in the always-rendered output toolbar, so it stays reachable once the panel is gone.
  var INPUTS_COLLAPSED_KEY = "dd-demo:inputs-collapsed";

  function setInputsCollapsed(collapsed) {
    $("#layout").classList.toggle("inputs-collapsed", collapsed);
    var btn = $("#toggle-input-btn");
    btn.setAttribute("aria-expanded", String(!collapsed));
    btn.title = collapsed ? "Show input panel" : "Hide input panel";
    $(".panel-toggle-icon").textContent = collapsed ? "›" : "‹";
    $(".panel-toggle-label").textContent = collapsed ? "Show panel" : "Hide panel";
    try { localStorage.setItem(INPUTS_COLLAPSED_KEY, collapsed ? "1" : "0"); } catch (e) {}
  }

  // --- Wiring -------------------------------------------------------------
  function wire() {
    $("#preset-select").addEventListener("change", function (e) { loadPreset(e.target.value); });

    $("#file-input").addEventListener("change", function (e) { addFiles(e.target.files); e.target.value = ""; });
    $("#folder-input").addEventListener("change", function (e) { addFiles(e.target.files); e.target.value = ""; });

    var dz = $("#drop-zone");
    ["dragenter", "dragover"].forEach(function (ev) {
      dz.addEventListener(ev, function (e) { e.preventDefault(); dz.classList.add("dragover"); });
    });
    ["dragleave", "dragend"].forEach(function (ev) {
      dz.addEventListener(ev, function () { dz.classList.remove("dragover"); });
    });
    dz.addEventListener("drop", function (e) {
      e.preventDefault();
      dz.classList.remove("dragover");
      handleDrop(e);
    });

    $("#doc-list").addEventListener("click", function (e) {
      var btn = e.target.closest("button[data-index]");
      if (btn) removeDoc(Number(btn.dataset.index));
    });
    $("#clear-btn").addEventListener("click", clearAll);

    $("#root-select").addEventListener("change", function (e) {
      rootIndex = e.target.value === "" ? null : Number(e.target.value);
      render();
    });
    ["#theme", "#expand-categories", "#expand-additional"].forEach(function (sel) {
      $(sel).addEventListener("change", function () { render(); });
    });
    $("#shadow").addEventListener("change", function () { delete OVERRIDES.shadow; render(); });
    $("#semantic").addEventListener("change", function (e) { setSemantic(e.target.checked); });

    $("#download-html-btn").addEventListener("click", downloadHtml);
    $("#download-csv-btn").addEventListener("click", downloadCsv);
    $("#download-excel-btn").addEventListener("click", downloadExcel);

    $("#toggle-input-btn").addEventListener("click", function () {
      setInputsCollapsed(!$("#layout").classList.contains("inputs-collapsed"));
    });
  }

  // --- URL overrides ------------------------------------------------------
  // Session-only knobs for automation and benchmarking, read once at start-up and never
  // persisted:
  //   ?preset=<key|index>      load this preset instead of the first one (e.g. synthetic10k)
  //   ?semantic=1|0            force the semantic toggle on/off, ignoring the saved preference
  //   ?model=<id>              embedding model id (forwarded to the worker)
  //   ?device=auto|wasm|webgpu execution device (forwarded to the worker)
  //   ?dtype=<string>          model quantisation, e.g. q8 / fp16 (forwarded to the worker)
  //   ?nogpu=1                 hide WebGPU from Transformers.js (exercises the WASM path)
  //   ?shadow=0                render into light DOM ({ shadow: false })
  function readOverrides() {
    var o = {};
    var params;
    try { params = new URLSearchParams(location.search); } catch (e) { return o; }
    var flag = function (name) {
      var v = params.get(name);
      return v === "1" ? true : v === "0" ? false : undefined;
    };
    if (params.get("preset")) o.preset = params.get("preset");
    if (flag("semantic") !== undefined) o.semantic = flag("semantic");
    ["model", "device", "dtype"].forEach(function (k) { if (params.get(k)) o[k] = params.get(k); });
    if (flag("nogpu") === true) o.nogpu = true;
    if (flag("shadow") === false) o.shadow = false;
    return o;
  }

  // --- Automation hooks ---------------------------------------------------
  // Stable handles for scripted checks and benchmarks.
  window.ddDemo = {
    presets: allPresets,
    loadPreset: loadPreset,
    render: function () { render(); },
    element: function () { return $("#output").firstElementChild; }, // the mounted <json-data-dictionary>
    embedder: function () { return semanticEmbedder; },
    worker: function () { return semanticWorker; },
    model: function () { return OVERRIDES.model || EMBEDDING_MODEL; }, // effective embedding model id
    lastTable: function () { return lastTable; },
    get lastRenderMs() { return lastRenderMs; }
  };

  // --- Bootstrap ----------------------------------------------------------
  function start() {
    if (!API) {
      var banner = $("#missing-bundle");
      if (banner) banner.hidden = false;
      return;
    }
    OVERRIDES = readOverrides();
    populatePresetSelect();
    wire();
    if (OVERRIDES.shadow === false) $("#shadow").checked = false;

    var savedCollapsed = null;
    try { savedCollapsed = localStorage.getItem(INPUTS_COLLAPSED_KEY); } catch (e) {}
    if (savedCollapsed === "1") setInputsCollapsed(true);

    if (allPresets().length) {
      var initial = OVERRIDES.preset != null ? findPresetIndex(OVERRIDES.preset) : 0;
      loadPreset(initial >= 0 ? initial : 0);
      if (initial < 0) addMessage("warning", "Unknown preset “" + OVERRIDES.preset + "” in the URL; loaded the first example instead.");
    } else {
      render(); // show the empty-state prompt
    }

    var savedSemantic = null;
    try { savedSemantic = localStorage.getItem(SEMANTIC_KEY); } catch (e) {}
    var wantSemantic = OVERRIDES.semantic !== undefined ? OVERRIDES.semantic : savedSemantic === "1";
    if (wantSemantic) {
      $("#semantic").checked = true;
      applySemantic(true); // not persisted: a ?semantic=1 visit must not change the saved preference
    }
  }

  start();
})();
