// Generates demo/presets.js (a `window.DEMO_PRESETS` global) from the schema
// fixtures in tests/fixtures/. Inlining the presets as a script avoids fetch/CORS
// so the demo works both over file:// and on GitHub Pages.
//
// Run via `npm run demo:presets` (or `npm run demo`). Output is gitignored.
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, dirname, basename, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURES = join(HERE, "..", "tests", "fixtures");

// Each preset is either a single fixture file (`only`) or a whole directory tree.
// `documents[].path` becomes the synthetic retrieval URI (`https://demo.local/<path>`)
// the library uses to resolve relative $refs, so for directory presets the path must
// reproduce the on-disk layout (e.g. `categories/demographics.json`, `common/defs.json`).
const SOURCES = [
  {
    label: "COVID-19 surveillance — single schema",
    description:
      "One self-contained array schema: enums with labels, string formats, ranges, and dependentRequired.",
    dir: "single_schema",
    only: "covid-patient-dataset.json"
  },
  {
    label: "Format showcase — single schema",
    description:
      "A single schema exercising every built-in string format and value kind (date, email, uuid, ip, …).",
    dir: "single_schema",
    only: "format-showcase-dataset.json"
  },
  {
    label: "Clinical trial — 5 interlinked schemas",
    description:
      "A root dataset whose row schema composes demographics, lab results and adverse events via allOf + relative $ref.",
    dir: "multiple_schema_1"
  },
  {
    label: "BCRPP CORE — 13 interlinked schemas",
    description:
      "A real breast-cancer cohort: 11 category files + shared $defs, JSON-Pointer $refs, sentinel codes and if/then skip patterns.",
    dir: "multiple_schema_2"
  }
];

/** Recursively collect `.json` files under `dir`, sorted, optionally limited to one basename. */
function jsonFilesUnder(dir, only) {
  const out = [];
  (function walk(d) {
    for (const entry of readdirSync(d).sort()) {
      const p = join(d, entry);
      if (statSync(p).isDirectory()) walk(p);
      else if (p.endsWith(".json") && (!only || basename(p) === only)) out.push(p);
    }
  })(dir);
  return out;
}

/** Normalise a filesystem path to POSIX separators for use as a synthetic URI path. */
const toPosix = (p) => p.split(sep).join("/");

const presets = SOURCES.map((src) => {
  const root = join(FIXTURES, src.dir);
  const files = jsonFilesUnder(root, src.only);
  if (files.length === 0) throw new Error(`No fixtures found for preset "${src.label}" under ${root}`);
  // Single-file presets: path is just the basename. Directory presets: path is
  // relative to the fixture directory root, preserving subdirectories.
  const documents = files.map((p) => ({
    path: src.only ? basename(p) : toPosix(relative(root, p)),
    schema: JSON.parse(readFileSync(p, "utf8"))
  }));
  return { label: src.label, description: src.description, documents };
});

const banner =
  "// AUTO-GENERATED by demo/build-presets.mjs — do not edit. Regenerate with `npm run demo:presets`.\n";
const out = banner + "window.DEMO_PRESETS = " + JSON.stringify(presets) + ";\n";
writeFileSync(join(HERE, "presets.js"), out, "utf8");

const docCount = presets.reduce((n, p) => n + p.documents.length, 0);
console.log(`Wrote demo/presets.js (${presets.length} presets, ${docCount} documents).`);
